# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1749, 932)
        self.MainWidget = QtWidgets.QWidget(Form)
        self.MainWidget.setGeometry(QtCore.QRect(0, 0, 1681, 901))
        self.MainWidget.setObjectName("MainWidget")
        self.groupBox = QtWidgets.QGroupBox(self.MainWidget)
        self.groupBox.setGeometry(QtCore.QRect(1460, 20, 211, 691))
        self.groupBox.setObjectName("groupBox")
        self.CurrentAlreadyMemNumLabel = QtWidgets.QLabel(self.groupBox)
        self.CurrentAlreadyMemNumLabel.setGeometry(QtCore.QRect(10, 20, 121, 17))
        self.CurrentAlreadyMemNumLabel.setObjectName("CurrentAlreadyMemNumLabel")
        self.WordsListViewer = QtWidgets.QListView(self.groupBox)
        self.WordsListViewer.setGeometry(QtCore.QRect(0, 60, 211, 641))
        self.WordsListViewer.setObjectName("WordsListViewer")
        self.ThisBatchWordsListListShowButton = QtWidgets.QPushButton(self.groupBox)
        self.ThisBatchWordsListListShowButton.setGeometry(QtCore.QRect(140, 90, 71, 28))
        self.ThisBatchWordsListListShowButton.setObjectName("ThisBatchWordsListListShowButton")
        self.AleradyMemListShowButton = QtWidgets.QPushButton(self.groupBox)
        self.AleradyMemListShowButton.setGeometry(QtCore.QRect(140, 60, 71, 28))
        self.AleradyMemListShowButton.setObjectName("AleradyMemListShowButton")
        self.ThisBatchNotReadyListShowButton = QtWidgets.QPushButton(self.groupBox)
        self.ThisBatchNotReadyListShowButton.setGeometry(QtCore.QRect(140, 120, 71, 28))
        self.ThisBatchNotReadyListShowButton.setObjectName("ThisBatchNotReadyListShowButton")
        self.resultGroup = QtWidgets.QGroupBox(self.MainWidget)
        self.resultGroup.setGeometry(QtCore.QRect(1160, 20, 231, 151))
        self.resultGroup.setObjectName("resultGroup")
        self.resultLabel = QtWidgets.QLabel(self.resultGroup)
        self.resultLabel.setGeometry(QtCore.QRect(10, 10, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.formLayoutWidget = QtWidgets.QWidget(self.resultGroup)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 110, 211, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.WordSearchForm = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.WordSearchForm.setContentsMargins(0, 0, 0, 0)
        self.WordSearchForm.setObjectName("WordSearchForm")
        self.WordSearchLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.WordSearchLineEdit.setObjectName("WordSearchLineEdit")
        self.WordSearchForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.WordSearchLineEdit)
        self.WordSearchButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.WordSearchButton.setObjectName("WordSearchButton")
        self.WordSearchForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.WordSearchButton)
        self.scrollArea = QtWidgets.QScrollArea(self.MainWidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 230, 1440, 661))
        self.scrollArea.setMinimumSize(QtCore.QSize(1440, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1440, 8000))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1440, 8000))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1401, 2004))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.scrollAreaHLayoutMain = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.scrollAreaHLayoutMain.setContentsMargins(0, 0, 0, 0)
        self.scrollAreaHLayoutMain.setObjectName("scrollAreaHLayoutMain")
        self.scrollAreaV1 = QtWidgets.QVBoxLayout()
        self.scrollAreaV1.setObjectName("scrollAreaV1")
        self.scrollAreaHLayoutMain.addLayout(self.scrollAreaV1)
        self.scrollAreaV2 = QtWidgets.QVBoxLayout()
        self.scrollAreaV2.setObjectName("scrollAreaV2")
        self.scrollAreaHLayoutMain.addLayout(self.scrollAreaV2)
        self.scrollAreaV3 = QtWidgets.QVBoxLayout()
        self.scrollAreaV3.setObjectName("scrollAreaV3")
        self.scrollAreaHLayoutMain.addLayout(self.scrollAreaV3)
        self.scrollAreaV4 = QtWidgets.QVBoxLayout()
        self.scrollAreaV4.setObjectName("scrollAreaV4")
        self.scrollAreaHLayoutMain.addLayout(self.scrollAreaV4)
        self.scrollAreaV5 = QtWidgets.QVBoxLayout()
        self.scrollAreaV5.setObjectName("scrollAreaV5")
        self.scrollAreaHLayoutMain.addLayout(self.scrollAreaV5)
        self.ImgHelpfulLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ImgHelpfulLabel.setGeometry(QtCore.QRect(50, 0, 951, 581))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(24)
        self.ImgHelpfulLabel.setFont(font)
        self.ImgHelpfulLabel.setObjectName("ImgHelpfulLabel")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.GetWordButton = QtWidgets.QPushButton(self.MainWidget)
        self.GetWordButton.setGeometry(QtCore.QRect(610, 170, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.GetWordButton.setFont(font)
        self.GetWordButton.setObjectName("GetWordButton")
        self.controlsGroup = QtWidgets.QGroupBox(self.MainWidget)
        self.controlsGroup.setGeometry(QtCore.QRect(10, 20, 451, 151))
        self.controlsGroup.setObjectName("controlsGroup")
        self.WordLabel = QtWidgets.QLabel(self.controlsGroup)
        self.WordLabel.setGeometry(QtCore.QRect(10, 10, 551, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(50)
        self.WordLabel.setFont(font)
        self.WordLabel.setObjectName("WordLabel")
        self.WordHistory = QtWidgets.QLabel(self.controlsGroup)
        self.WordHistory.setGeometry(QtCore.QRect(10, 90, 431, 51))
        self.WordHistory.setObjectName("WordHistory")
        self.MemNoButton = QtWidgets.QPushButton(self.MainWidget)
        self.MemNoButton.setGeometry(QtCore.QRect(100, 170, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.MemNoButton.setFont(font)
        self.MemNoButton.setObjectName("MemNoButton")
        self.layoutWidget = QtWidgets.QWidget(self.MainWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1560, 860, 308, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.numberSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.numberSpinBox.setObjectName("numberSpinBox")
        self.horizontalLayout.addWidget(self.numberSpinBox)
        self.styleCombo = QtWidgets.QComboBox(self.layoutWidget)
        self.styleCombo.setObjectName("styleCombo")
        self.styleCombo.addItem("")
        self.styleCombo.addItem("")
        self.styleCombo.addItem("")
        self.horizontalLayout.addWidget(self.styleCombo)
        self.printButton = QtWidgets.QPushButton(self.layoutWidget)
        self.printButton.setObjectName("printButton")
        self.horizontalLayout.addWidget(self.printButton)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.OpenFarmButton = QtWidgets.QPushButton(self.MainWidget)
        self.OpenFarmButton.setGeometry(QtCore.QRect(1460, 720, 91, 81))
        self.OpenFarmButton.setObjectName("OpenFarmButton")
        self.MemYesButton = QtWidgets.QPushButton(self.MainWidget)
        self.MemYesButton.setGeometry(QtCore.QRect(610, 170, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.MemYesButton.setFont(font)
        self.MemYesButton.setAutoFillBackground(False)
        self.MemYesButton.setObjectName("MemYesButton")
        self.ShowAnsButton = QtWidgets.QPushButton(self.MainWidget)
        self.ShowAnsButton.setGeometry(QtCore.QRect(100, 170, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.ShowAnsButton.setFont(font)
        self.ShowAnsButton.setObjectName("ShowAnsButton")
        self.MemNoMoreButton = QtWidgets.QPushButton(self.MainWidget)
        self.MemNoMoreButton.setGeometry(QtCore.QRect(1460, 870, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(9)
        self.MemNoMoreButton.setFont(font)
        self.MemNoMoreButton.setObjectName("MemNoMoreButton")
        self.MoreImageButton = QtWidgets.QPushButton(self.MainWidget)
        self.MoreImageButton.setGeometry(QtCore.QRect(1460, 804, 91, 51))
        self.MoreImageButton.setObjectName("MoreImageButton")
        self.WordGroup = QtWidgets.QGroupBox(self.MainWidget)
        self.WordGroup.setGeometry(QtCore.QRect(470, 20, 661, 151))
        self.WordGroup.setObjectName("WordGroup")
        self.WordDetailScrollArea = QtWidgets.QScrollArea(self.WordGroup)
        self.WordDetailScrollArea.setGeometry(QtCore.QRect(10, 20, 641, 111))
        self.WordDetailScrollArea.setWidgetResizable(True)
        self.WordDetailScrollArea.setObjectName("WordDetailScrollArea")
        self.WordDetailScrollAreaContent = QtWidgets.QWidget()
        self.WordDetailScrollAreaContent.setGeometry(QtCore.QRect(0, 0, 622, 200))
        self.WordDetailScrollAreaContent.setMinimumSize(QtCore.QSize(0, 200))
        self.WordDetailScrollAreaContent.setObjectName("WordDetailScrollAreaContent")
        self.WordDetailtextBrowser = QtWidgets.QTextBrowser(self.WordDetailScrollAreaContent)
        self.WordDetailtextBrowser.setGeometry(QtCore.QRect(0, 0, 621, 661))
        self.WordDetailtextBrowser.setObjectName("WordDetailtextBrowser")
        self.WordDetailScrollArea.setWidget(self.WordDetailScrollAreaContent)
        self.ShowImgAutoCheckBox = QtWidgets.QCheckBox(self.WordGroup)
        self.ShowImgAutoCheckBox.setGeometry(QtCore.QRect(10, 130, 97, 21))
        self.ShowImgAutoCheckBox.setObjectName("ShowImgAutoCheckBox")
        self.WordSmallLabel = QtWidgets.QLabel(self.WordGroup)
        self.WordSmallLabel.setGeometry(QtCore.QRect(50, 0, 441, 17))
        self.WordSmallLabel.setObjectName("WordSmallLabel")
        self.ShowImgWhenMemNoAutoCheckBox = QtWidgets.QCheckBox(self.WordGroup)
        self.ShowImgWhenMemNoAutoCheckBox.setGeometry(QtCore.QRect(100, 130, 161, 21))
        self.ShowImgWhenMemNoAutoCheckBox.setObjectName("ShowImgWhenMemNoAutoCheckBox")
        self.NextBatchButton = QtWidgets.QPushButton(self.MainWidget)
        self.NextBatchButton.setGeometry(QtCore.QRect(1230, 170, 71, 61))
        self.NextBatchButton.setObjectName("NextBatchButton")
        self.BatchLengthLineEdit = QtWidgets.QLineEdit(self.MainWidget)
        self.BatchLengthLineEdit.setGeometry(QtCore.QRect(1300, 170, 51, 61))
        self.BatchLengthLineEdit.setObjectName("BatchLengthLineEdit")
        self.ShowImageButton = QtWidgets.QPushButton(self.MainWidget)
        self.ShowImageButton.setGeometry(QtCore.QRect(240, 170, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.ShowImageButton.setFont(font)
        self.ShowImageButton.setObjectName("ShowImageButton")
        self.MemNotSureButton = QtWidgets.QPushButton(self.MainWidget)
        self.MemNotSureButton.setGeometry(QtCore.QRect(400, 170, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.MemNotSureButton.setFont(font)
        self.MemNotSureButton.setAutoFillBackground(False)
        self.MemNotSureButton.setObjectName("MemNotSureButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.MainWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(1580, 820, 154, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previewStatus = QtWidgets.QCheckBox(self.layoutWidget1)
        self.previewStatus.setObjectName("previewStatus")
        self.horizontalLayout_2.addWidget(self.previewStatus)
        self.previewButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.previewButton.setObjectName("previewButton")
        self.horizontalLayout_2.addWidget(self.previewButton)
        self.CounterTimeLabel = QtWidgets.QLabel(self.MainWidget)
        self.CounterTimeLabel.setGeometry(QtCore.QRect(1580, 710, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(25)
        self.CounterTimeLabel.setFont(font)
        self.CounterTimeLabel.setObjectName("CounterTimeLabel")
        self.CounterTimeButton = QtWidgets.QPushButton(self.MainWidget)
        self.CounterTimeButton.setGeometry(QtCore.QRect(1570, 770, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.CounterTimeButton.setFont(font)
        self.CounterTimeButton.setObjectName("CounterTimeButton")
        self.TakeNotetextEdit = QtWidgets.QTextEdit(self.MainWidget)
        self.TakeNotetextEdit.setGeometry(QtCore.QRect(950, 170, 171, 61))
        self.TakeNotetextEdit.setObjectName("TakeNotetextEdit")
        self.TakeNotePublishpushButton = QtWidgets.QPushButton(self.MainWidget)
        self.TakeNotePublishpushButton.setGeometry(QtCore.QRect(1120, 170, 41, 61))
        self.TakeNotePublishpushButton.setObjectName("TakeNotePublishpushButton")
        self.MemYesButton.raise_()
        self.MemNotSureButton.raise_()
        self.groupBox.raise_()
        self.resultGroup.raise_()
        self.scrollArea.raise_()
        self.GetWordButton.raise_()
        self.controlsGroup.raise_()
        self.layoutWidget.raise_()
        self.OpenFarmButton.raise_()
        self.ShowAnsButton.raise_()
        self.MemNoMoreButton.raise_()
        self.MoreImageButton.raise_()
        self.WordGroup.raise_()
        self.NextBatchButton.raise_()
        self.BatchLengthLineEdit.raise_()
        self.ShowImageButton.raise_()
        self.MemNoButton.raise_()
        self.layoutWidget.raise_()
        self.CounterTimeLabel.raise_()
        self.CounterTimeButton.raise_()
        self.TakeNotetextEdit.raise_()
        self.TakeNotePublishpushButton.raise_()
        self.URLDownloadButton = QtWidgets.QPushButton(Form)
        self.URLDownloadButton.setGeometry(QtCore.QRect(380, 900, 75, 25))
        self.URLDownloadButton.setObjectName("URLDownloadButton")
        self.URLDownloadInputlineEdit = QtWidgets.QLineEdit(Form)
        self.URLDownloadInputlineEdit.setGeometry(QtCore.QRect(10, 900, 361, 23))
        self.URLDownloadInputlineEdit.setObjectName("URLDownloadInputlineEdit")
        self.ImgHelpfulYesButton = QtWidgets.QPushButton(Form)
        self.ImgHelpfulYesButton.setGeometry(QtCore.QRect(780, 900, 75, 25))
        self.ImgHelpfulYesButton.setObjectName("ImgHelpfulYesButton")
        self.ImgHelpfulNoButton = QtWidgets.QPushButton(Form)
        self.ImgHelpfulNoButton.setGeometry(QtCore.QRect(610, 900, 161, 25))
        self.ImgHelpfulNoButton.setObjectName("ImgHelpfulNoButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "元单词 One Word V1.0（Author: Chen Yiwen cywgoog@gmail.com）"))
        self.groupBox.setTitle(_translate("Form", "本次已完成"))
        self.CurrentAlreadyMemNumLabel.setText(_translate("Form", "本次已记忆：0"))
        self.ThisBatchWordsListListShowButton.setText(_translate("Form", "任务列表"))
        self.AleradyMemListShowButton.setText(_translate("Form", "已浇水"))
        self.ThisBatchNotReadyListShowButton.setText(_translate("Form", "待浇水"))
        self.resultGroup.setTitle(_translate("Form", "Debug"))
        self.resultLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt;\">系统消息</span></p><p><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.WordSearchButton.setText(_translate("Form", "Search"))
        self.ImgHelpfulLabel.setText(_translate("Form", "该单词不适合用图片记忆"))
        self.GetWordButton.setText(_translate("Form", "OK,下一个（D）"))
        self.controlsGroup.setTitle(_translate("Form", "主要信息"))
        self.WordLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:48pt;\">WORD</span></p></body></html>"))
        self.WordHistory.setText(_translate("Form", "单词历史"))
        self.MemNoButton.setText(_translate("Form", "我忘了o(╥﹏╥)o（A）"))
        self.label.setText(_translate("Form", "打印份数:"))
        self.styleCombo.setItemText(0, _translate("Form", "A3"))
        self.styleCombo.setItemText(1, _translate("Form", "A4"))
        self.styleCombo.setItemText(2, _translate("Form", "A5"))
        self.printButton.setText(_translate("Form", "打印"))
        self.label_2.setText(_translate("Form", "纸张类型:"))
        self.OpenFarmButton.setText(_translate("Form", "进入单词农场"))
        self.MemYesButton.setText(_translate("Form", "我记得(*^▽^*)（D）"))
        self.ShowAnsButton.setText(_translate("Form", "开解释（q）"))
        self.MemNoMoreButton.setText(_translate("Form", "不要这个单词"))
        self.MoreImageButton.setText(_translate("Form", "需要更多图片"))
        self.WordGroup.setTitle(_translate("Form", "单词区"))
        self.WordDetailtextBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">单词详情内容</span></p></body></html>"))
        self.ShowImgAutoCheckBox.setText(_translate("Form", "自动加载图"))
        self.WordSmallLabel.setText(_translate("Form", "Small Word"))
        self.ShowImgWhenMemNoAutoCheckBox.setText(_translate("Form", "不记得时，自动加载图"))
        self.NextBatchButton.setText(_translate("Form", "下一批"))
        self.BatchLengthLineEdit.setText(_translate("Form", "30"))
        self.ShowImageButton.setText(_translate("Form", "开图（p）"))
        self.MemNotSureButton.setText(_translate("Form", "我不确定（S）"))
        self.previewStatus.setText(_translate("Form", "全屏预览"))
        self.previewButton.setText(_translate("Form", "预览"))
        self.CounterTimeLabel.setText(_translate("Form", "Time"))
        self.CounterTimeButton.setText(_translate("Form", "开关计时器"))
        self.TakeNotetextEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">做笔记</p></body></html>"))
        self.TakeNotePublishpushButton.setText(_translate("Form", "发布\n"
"笔记"))
        self.URLDownloadButton.setText(_translate("Form", "下载新图"))
        self.URLDownloadInputlineEdit.setText(_translate("Form", "输入图片URL"))
        self.ImgHelpfulYesButton.setText(_translate("Form", "图片有用"))
        self.ImgHelpfulNoButton.setText(_translate("Form", "图片无用，不再显示"))
